name: coroot

volumes:
  prometheus_data: {}
  clickhouse_data: {}
  clickhouse_logs: {}
  coroot_data: {}
  node_agent_data: {}
  cluster_agent_data: {}

services:
  coroot:
    restart: always
    image: ghcr.io/coroot/coroot${LICENSE_KEY:+-ee} # set 'coroot-ee' as the image if LICENSE_KEY is defined
    pull_policy: always
    user: root
    volumes:
      - coroot_data:/data
    ports:
      - 8080:8080
    command:
      - '--data-dir=/data'
      - '--bootstrap-prometheus-url=http://prometheus:9090'
      - '--bootstrap-refresh-interval=1s'
      - '--bootstrap-clickhouse-address=clickhouse:9000'
    environment:
      - LICENSE_KEY=${LICENSE_KEY:-}
      - CLICKHOUSE_ADDR=http://clickhouse:8123
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=corootpass
    depends_on:
      - clickhouse
      - prometheus

  node-agent:
    restart: always
    image: ghcr.io/coroot/coroot-node-agent
    pull_policy: always
    privileged: true
    pid: "host"
    volumes:
      - /sys/kernel/tracing:/sys/kernel/tracing
      - /sys/kernel/debug:/sys/kernel/debug
      - /sys/fs/cgroup:/host/sys/fs/cgroup
      - node_agent_data:/data
    command:
      - '--collector-endpoint=http://coroot:8080'
      - '--cgroupfs-root=/host/sys/fs/cgroup'
      - '--wal-dir=/data'
      - '--scrape-interval=5s'
    # - '--api-key=YOUR_API_KEY'

  cluster-agent:
    restart: always
    image: ghcr.io/coroot/coroot-cluster-agent
    pull_policy: always
    volumes:
      - cluster_agent_data:/data
    command:
      - '--coroot-url=http://coroot:8080'
      - '--metrics-scrape-interval=15s'
      - '--metrics-wal-dir=/data'
    depends_on:
      - coroot

  prometheus:
    restart: always
    image: prom/prometheus:latest
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
      - '--web.enable-remote-write-receiver'
      - '--storage.tsdb.retention.time=15d'
      - '--storage.tsdb.retention.size=512MB'
      - '--storage.tsdb.wal-compression'
      - '--storage.tsdb.no-lockfile'
    ports:
      - '127.0.0.1:9090:9090'

  clickhouse:
    restart: always
    image: clickhouse/clickhouse-server:latest
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_logs:/var/log/clickhouse-server
    environment:
      - CLICKHOUSE_DB=clickhouse
      - CLICKHOUSE_USER=user
      - CLICKHOUSE_PASSWORD=corootpass
    ports:
      - '127.0.0.1:9000:9000'
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
  
  iperf3-server:
    image: networkstatic/iperf3
    command: "-s -p 5201 --verbose"
    ports:
      - "5201:5201"
    labels:
      - "coroot.monitored=true"
      - "coroot.service.type=streaming"
      - "coroot.logs.enabled=true"

  iperf3-client:
    image: networkstatic/iperf3
    command: "-c iperf3-server -p 5201 -t 0 -b 10M --verbose"
    restart: always
    depends_on:
      - iperf3-server
    labels:
      - "coroot.monitored=true"
      - "coroot.service.type=streaming"
      - "coroot.logs.enabled=true"
