global:
  scrape_interval: 500ms
  evaluation_interval: 500ms
  scrape_timeout: 200ms

scrape_configs:
  - job_name: 'node-agent'
    static_configs:
      - targets: ['node-agent:9100']
    scrape_interval: 500ms
    scrape_timeout: 200ms

  - job_name: 'cluster-agent'
    static_configs:
      - targets: ['cluster-agent:9100']
    scrape_interval: 500ms
    scrape_timeout: 200ms

  - job_name: 'coroot'
    static_configs:
      - targets: ['coroot:8080']
    scrape_interval: 500ms
    scrape_timeout: 200ms 